[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"
  handler = "index.handler"
